#!/usr/bin/env bash

# Temporarily not caring about referenced variables that are not assigned here.
# shellcheck disable=2154

# SC2015: You can often see that I use: A && B || C as if-then-else.
# This is generally not correct, if A is true but B is false, C will run.
# But it's safe to use when B is just a variable definition or a command that is never false.

set -eo pipefail

MAIS_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)" || exit 1
readonly MAIS_ROOT

# BEGIN MAIS MODULE LOADER
# Bootstrap the module loader.
# shellcheck source=lib/core/loader.sh
source "$MAIS_ROOT/lib/core/loader.sh"

mais_load_module "lib/core/config.sh"
mais_load_module "lib/core/log.sh"
mais_load_module "lib/core/validate.sh"
mais_load_module "lib/core/prompt.sh"
mais_load_module "lib/core/run.sh"
mais_load_module "lib/core/sudo.sh"

mais_load_module "lib/distro/detect.sh"
mais_load_module "lib/distro/arch.sh"

mais_load_module "lib/commands/arch-install.sh"
mais_load_module "lib/commands/backup.sh"
mais_load_module "lib/commands/update-mirrors.sh"
mais_load_module "lib/commands/install-dotfiles.sh"
mais_load_module "lib/commands/install-aurhelper.sh"
mais_load_module "lib/commands/install-programs.sh"
mais_load_module "lib/commands/configure.sh"
mais_load_module "lib/commands/experimental-clean-home.sh"
mais_load_module "lib/commands/install.sh"
# END MAIS MODULE LOADER

### Functions ###

# Helper function to report incorrect usage.
invalid_option() {
    eprint "Invalid option '$1'
Try '$program_name help' for more information."
}

# Print help message that list all options and flags available.
print_help() {
    printf "Usage: %s command [options]

    -- Commands --

        help                    Print this help message and exit

        arch-install partition_mode

                Install ArchLinux according to the **Installation Guide** https://wiki.archlinux.org/title/Installation_guide

                The script will default to UEFI and fallback to BIOS if needed
                
                'partition_mode' should be one of 'vm', 'main', 'x220' or 'mounted' for a custom made partition table

                You can read more about 'partition_mode's in README.md

                Designed to run on the live environment.

        install-dotfiles [dotfiles_url]

                Install dotfiles to your home directory

                'dotfiles_url' is optional and defaults to 'https://github.com/themamiza/dotfiles'

                This command will ignore 'dotfiles_url' altogether if there's a '~/rp/dotfiles' and use that instead

        install-aurhelper aurhelper

                Install aurhelper for the user

                'aurhelper' should be one of 'yay' or 'paru'

                The script prefers 'yay' and will install it on it's own when needed

        install-programs [TAG]

                Install programs from a 'programs.csv' file

                Read 'programs.csv' for more information about tags and the file itself
                
                
        configure           Do various system configurations (See README.md for details)

        backup [backup_name]

                Take a backup from a set of pre-defined files

                'backup_name' is optional and is the name of the directory of the final backup (~/backup_name)
                Defaults to '~/backup_\$(date \"+%%Y-%%m-%%d_%%H:%%M\")'

        update-mirrors          Runs a reflector command to fetch faster mirrors

                Here is what a reflector command looks like

                \`reflector --country Germany --latest 16 --protocol https --sort rate --save /etc/pacman.d/mirrorlist\`

        install                 Install \`%s\` for local usage
                
                Will install to '/usr/local/bin'

    -- Options --

        -v | --verbose          Print as much as possible

        -q | --quiet            Be as quiet as possible


        **Commands might interactively ask for information, you can avoid this by providing them at the command line**

        -u | --username
        -h | --hostname
        -t | --timezone

Written by: drogoniza@gmail.com
" "$program_name" "$program_name"
}

### Handling arguments ###

if [[ $# -lt 1 ]]; then
    print_help
    exit 1
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        "help") help=true; shift;;

        "arch-install")
            [ -z "$2" ] && eprint "\`arch-install\` -> you should provide a 'parition_mode' (vm, main, X220, mounted)."
            args_arch_install=true
            # shellcheck disable=2015,2034
            re_match "$2" "^(vm|main|x220|mounted)$" && partition_mode="$2" || eprint "'$2' is not a valid partitioning mode."
            shift 2
            ;;

        "install-dotfiles")
            args_install_dotfiles=true; shift

            if [[ $# -gt 0 && "$1" != -* ]]; then
                # shellcheck disable=2034
                dotfiles_url="$1"
                shift
            fi
            ;;

        "install-aurhelper")
            [ -z "$2" ] && eprint "\`install-aurhelper\` -> you should provide a 'aurhelper' (yay, paru)."
            args_install_aurhelper=true 
            # shellcheck disable=2015,2034
            re_match "$2" "^(yay|paru)$" && aurhelper="$2" || eprint "'$2' is not a valid aurhelper."
            shift 2
            ;;

        "install-programs")
            args_install_programs=true
            [ -z "$2" ] && programs="ALL" && shift && continue
            # shellcheck disable=2015,2034
            re_match "$2" "^(X11|DWM|WAYLAND|HYPRLAND|DEV|PYTHON|CLANG|LUA|BASH|JS|EXTRA|VIRT|ALL)$" && programs="$2" || eprint "'$2' is not a valid tag."
            shift 2
            ;;

        "configure") args_configure=true; shift;;

        "experimental-clean-home") args_clean_home=true; shift;;

        "backup")
            args_backup=true
            [ -z "$2" ] && backup_name="backup_$(date "+%Y-%m-%d_%H:%M")" && shift && continue
            # shellcheck disable=2015,2034
            re_match "$2" "$regex_valid_directory" && backup_name="$2" || eprint ""
            shift 2
            ;;

        "update-mirrors") args_update_mirrors=true; shift;;

        "install") args_install=true; shift;;

        
        "-v"|"--verbose") 
            verbose=true
            # shellcheck disable=2034
            cmd_suffix=""
            shift;;

        "-q"|"--quiet") quiet=true; shift;;

        "-u"|"--username")
            if [ -z "$2" ]; then
                eprint "'-u' -> You should provide a username."
            fi
            username="$2"
            if ! re_match "$username" "$regex_valid_username"; then
                eprint "Username '$username' is not valid.\nGive a username beginning with a letter, with only lowercase letters, - or _."
            fi
            shift 2
            ;;

        "-h"|"--hostname")
            if [ -z "$2" ]; then
                eprint "'-h' -> You should provide a hostname."
            fi
            hostname="$2"
            if ! re_match "$hostname" "$regex_valid_hostname"; then
                eprint "Hostname '$hostname' is not valid.\nGive a hostname beginning with a letter, with only lowercase letters, - or _."
            fi
            shift 2
            ;;

        "-t"|"--timezone")
            if [ -z "$2" ]; then
                eprint "'-t' -> You should provide a timezone."
            fi
            timezone="$2"
            if ! [ -f "/usr/share/zoneinfo/$timezone" ]; then
                eprint "Timezone '$timezone' is not valid.\nView valid timezones: \`timezonectl list-timezones\`"
            fi
            shift 2
            ;;

        *) invalid_option "$1";;
    esac
done

$verbose && $quiet && eprint "Can't use '-v' with '-q'."

# Set username to current user, unless running by root or explicitly specifying the username through arguments.
! isRoot && [ -z "$username" ] && username="$(id -un)"

# If running as root through `sudo`; set username to $SUDO_USER 
isRoot && [ -n "$SUDO_USER" ] && username="$SUDO_USER"

# Set hostname to current hostname if not already provided.
[ -z "$hostname" ] && hostname="$(hostnamectl hostname 2>/dev/null || cat /etc/hostname)"

[ -n "$help" ] && print_help && exit 0

[[ -n "$args_arch_install" ]] && command_arch_install

[[ -n "$args_install_dotfiles" ]] && command_install_dotfiles

[[ -n "$args_install_aurhelper" ]] && command_install_aurhelper

[[ -n "$args_install_programs" ]] && command_install_programs

[[ -n "$args_configure" ]] && command_configure

[[ -n "$args_clean_home" ]] && command_experimental_clean_home

[[ -n "$args_backup" ]] && command_backup

[[ -n "$args_update_mirrors" ]] && command_update_mirrors

[[ -n "$args_install" ]] && command_install
