#!/usr/bin/env bash

# Temporarily not caring about referenced variables that are not assigned here.
# shellcheck disable=2154

# SC2015: You can often see that I use: A && B || C as if-then-else.
# This is generally not correct, if A is true but B is false, C will run.
# But it's safe to use when B is just a variable definition or a command that is never false.

set -eo pipefail

MAIS_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)" || exit 1
readonly MAIS_ROOT

# Bootstrap the module loader.
# shellcheck source=lib/core/loader.sh
source "$MAIS_ROOT/lib/core/loader.sh"

mais_load_module "lib/core/config.sh"
mais_load_module "lib/core/log.sh"
mais_load_module "lib/core/validate.sh"
mais_load_module "lib/core/prompt.sh"
mais_load_module "lib/core/run.sh"
mais_load_module "lib/core/sudo.sh"

mais_load_module "lib/distro/detect.sh"
mais_load_module "lib/distro/arch.sh"

mais_load_module "lib/commands/backup.sh"
mais_load_module "lib/commands/update-mirrors.sh"
mais_load_module "lib/commands/install-dotfiles.sh"
mais_load_module "lib/commands/install-aurhelper.sh"
mais_load_module "lib/commands/install-programs.sh"
mais_load_module "lib/commands/configure.sh"
mais_load_module "lib/commands/experimental-clean-home.sh"

### Functions ###

# Helper function to report incorrect usage.
invalid_option() {
    eprint "Invalid option '$1'
Try '$program_name help' for more information."
}

# Print help message that list all options and flags available.
print_help() {
    printf "Usage: %s command [options]

    -- Commands --

        help                    Print this help message and exit

        arch-install partition_mode

                Install ArchLinux according to the **Installation Guide** https://wiki.archlinux.org/title/Installation_guide

                The script will default to UEFI and fallback to BIOS if needed
                
                'partition_mode' should be one of 'vm', 'main', 'x220' or 'mounted' for a custom made partition table

                You can read more about 'partition_mode's in README.md

                Designed to run on the live environment.

        install-dotfiles [dotfiles_url]

                Install dotfiles to your home directory

                'dotfiles_url' is optional and defaults to 'https://github.com/themamiza/dotfiles'

                This command will ignore 'dotfiles_url' altogether if there's a '~/rp/dotfiles' and use that instead

        install-aurhelper aurhelper

                Install aurhelper for the user

                'aurhelper' should be one of 'yay' or 'paru'

                The script prefers 'yay' and will install it on it's own when needed

        install-programs [TAG]

                Install programs from a 'programs.csv' file

                Read 'programs.csv' for more information about tags and the file itself
                
                
        configure           Do various system configurations (See README.md for details)

        backup [backup_name]

                Take a backup from a set of pre-defined files

                'backup_name' is optional and is the name of the directory of the final backup (~/backup_name)
                Defaults to '~/backup_\$(date \"+%%Y-%%m-%%d_%%H:%%M\")'

        update-mirrors          Runs a reflector command to fetch faster mirrors

                Here is what a reflector command looks like

                \`reflector --country Germany --latest 16 --protocol https --sort rate --save /etc/pacman.d/mirrorlist\`

        install                 Install \`%s\` for local usage
                
                Will install to '/usr/local/bin'

    -- Options --

        -v | --verbose          Print as much as possible

        -q | --quiet            Be as quiet as possible


        **Commands might interactively ask for information, you can avoid this by providing them at the command line**

        -u | --username
        -h | --hostname
        -t | --timezone

Written by: drogoniza@gmail.com
" "$program_name" "$program_name"
}

ensure_mount_point() {
    if mountpoint -q /mnt; then
        wprint "'/mnt' is already in use."
        yes_no "Do you want to unmount before continuing? (Y/N): " && umount -R /mnt && return
        nprint "Proceeding with existing mount points." && return 1
    else
        return 0
    fi
}

# label -> label type: dos/gpt
# size  -> measured in sectors; each sector being 512 bytes.
partition_main() {
    eprint "Not implemented!"
}

partition_x220() {
    case "$bios_or_uefi" in
        "UEFI")
            printf "label: gpt
start=,size=2000000,type=U
start=,size=64000000
start=,size=416000000
start=,size=,type=S\n" | sfdisk /dev/sda --wipe always
        mkfs.fat  -F 32 /dev/sda1
        mkfs.ext4 -qF /dev/sda2
        mkfs.ext4 -qF /dev/sda3
        mkswap /dev/sda4

        mount /dev/sda2 /mnt
        mount --mkdir /dev/sda1 /mnt/efi
        mount --mkdir /dev/sda3 /mnt/home
        swapon /dev/sda4
        ;;

        "BIOS") printf "label: dos
start=,size=64000000
start=,size=\n" | sfdisk /dev/sda --wipe always
        mkfs.ext4 -qF /dev/sda1
        mkfs.ext4 -qF /dev/sda2

        mount /dev/sda1 /mnt
        mount --mkdir /dev/sda2 /mnt/home
        ;;
    esac
}

partition_vm() {
    case "$bios_or_uefi" in
        "UEFI") 
            printf "label: gpt
start=,size=2000000,type=U
start=,size=64000000
start=,size=\n" | sfdisk /dev/vda --wipe always
        mkfs.fat  -F 32 /dev/vda1
        mkfs.ext4 -qF /dev/vda2
        mkfs.ext4 -qF /dev/vda3

        mount /dev/vda2 /mnt
        mount --mkdir /dev/vda1 /mnt/efi
        mount --mkdir /dev/vda3 /mnt/home
        ;;

        "BIOS") printf "label: dos
start=,size=64000000
start=,size=\n" | sfdisk /dev/vda --wipe always
        mkfs.ext4 -qF /dev/vda1
        mkfs.ext4 -qF /dev/vda2

        mount /dev/vda1 /mnt
        mount --mkdir /dev/vda2 /mnt/home
        ;;
    esac
}

# Why do I pass all the variables as arguments? Explained in `arch_install`.
# args: username pass1 hostname timezone bios_or_uefi bootloader_id efi_directory disk_to_install cmd_suffix
# TODO: Fix `arch_install_run_in_chroot` not executing.
arch_install_run_in_chroot() {
    # Renaming vars only for more readability.
    local username="$1"
    local pass1="$2"
    local hostname="$3"
    local timezone="$4"
    local bios_or_uefi="$5"
    local bootloader_id="$6"
    local efi_directory="$7"
    local disk_to_install="$8"
    local cmd_suffix="$9"
    local program_name="${10}"
    
    # TODO: Should this be done during initial installation?
    # if command -v nvim >/dev/null 2>&1; then
    #     if [ ! -e "/usr/bin/vim" ] || [ -L "/usr/bin/vim" ]; then
    #         sprint "Creating symlink: vim -> nvim."
    #         ln -sf /usr/bin/nvim /usr/bin/vim
    #     fi
    #     if [ ! -e "/usr/bin/vi" ] || [ -L "/usr/bin/vi" ]; then
    #         sprint "Creating symlink: vi -> nvim."
    #         ln -sf /usr/bin/nvim /usr/bin/vi
    #     fi
    # fi
    # printf "\n"

    sprint "Setting timezone to '$timezone'.\n"
    ln -sf "/usr/share/zoneinfo/$timezone" /etc/localtime

    sprint "Configuring hardware clock."
    hwclock --systohc

    sprint "Configuring locale."
    sed -i 's/^#\s*\(en_US.UTF-8\)/\1/' /etc/locale.gen
    eval "locale-gen $cmd_suffix"
    printf "LANG=en_US.UTF-8\n" > /etc/locale.conf

    sprint "Setting hostname to '$hostname'."
    printf "%s\n" "$hostname" > /etc/hostname

    # TODO: Check if it's actually necessary to run this command.
    # nprint "Creating new initramfs."
    # eval "mkinitcpio -P $cmd_suffix"

    sprint "Installing grub bootloader to /efi."
    case "$bios_or_uefi" in
        "UEFI") eval "grub-install --target=x86_64-efi --efi-directory=$efi_directory --bootloader-id=$bootloader_id $cmd_suffix";;
        "BIOS") eval "grub-install --target=i386-pc $disk_to_install";;
    esac

    sprint "Re-creating grub configuration."
    eval "grub-mkconfig -o /boot/grub/grub.cfg $cmd_suffix"

    nprint "Creating new user '$username'."
    if ! id "$username" >/dev/null 2>&1; then
        useradd --create-home --user-group --groups wheel --shell /bin/bash "$username"
    fi

    sprint "Changing password for new user."
    echo "$username:$pass1" | chpasswd
    unset pass1 pass2

    wheel_can_sudo

    sprint "Enabling NerworkManager."
    eval "systemctl enable NetworkManager $cmd_suffix"

    # This should be the last thing done.
    if [ -f "/etc/installation.date" ]; then
        wprint "'/etc/installation.date' already exists."
        yes_no "Do you wish to overwrite it? (Y/N): " && date > /etc/installation.date
    fi
}

arch_install() {
    printf "The rest of the installation assumes you have
1. an internet connection. \`iwctl\`
2. synchronized system clock. \`timedatectl set-ntp true\`
3. configured your filesystem and mounted your root at '/mnt'. \`fdisk\`\n
SHOULD NOT BE RAN ON AN EXISTING ARCH INSTALLAION!\n\n"
    yes_no "Continue (Y/N): " || exit 0

    ask_username

    # Get password for said user.
    while true; do
        printf "%s's password: " "$username" && read -rs pass1 && printf "\n"
        printf "Retype password: " && read -rs pass2 && printf "\n"
        [ -n "$pass1" ] && [ "$pass1" = "$pass2" ] && unset pass2 && break
        wprint "Passwords do not match or are empty. Try again."
    done

    ask_hostname

    # Change this so it uses fzf for easier access.
    if [ -z "$timezone" ]; then
        while true; do
            printf "Timezone (Region/City) [UTC]: " && read -r timezone
            timezone="${timezone:-UTC}"
            [ -f "/usr/share/zoneinfo/$timezone" ] && break
            wprint "Timezone not valid. A valid timezone looks like -> \"US/Eastern\""
        done
    fi

    # TODO: Print configuration before installing.
    
    eval "cat /sys/firmware/efi/fw_platform_size $cmd_suffix" || bios_or_uefi="BIOS"

    sprint "Checking internet connection...\n"
    check_internet_connection || eprint "Can't reach the web."
    sprint "Internet connection is available.\n"

    base_packages=(base linux-lts linux-firmware grub networkmanager sudo neovim)
    [ "$bios_or_uefi" = "UEFI" ] && base_packages+=(efibootmgr)
    sprint "Bootstraping the system...\n"
    pacstrap -K /mnt "${base_packages[@]}"
    sprint "Done bootstrapping the system.\n"

    sprint "Generating fstab...\n"
    genfstab -U /mnt >> /mnt/etc/fstab
    sprint "fstab written to /mnt/etc/fstab.\n"

    # Exporting the function to later be passed to arch-chroot as a command.
    # That is why all the variables are passed manually.
    # TODO: Investigate if it can be done any other way.
    # arch_install_run_in_chroot() { # -> args: username pass1 hostname timezone bios_or_uefi bootloader_id efi_directory disk_to_install
    local exported_functions=(arch_install_run_in_chroot wheel_can_sudo trap_cleanup_sudoers nprint sprint wprint)
    for fn in "${exported_functions[@]}"; do
        # shellcheck disable=2163
        export -f "$fn"
    done

    arch-chroot /mnt /bin/sh -c "arch_install_run_in_chroot '$username' '$pass1' '$hostname' '$timezone' '$bios_or_uefi' '$bootloader_id' '$efi_directory' '$disk_to_install' '$cmd_suffix' '$program_name'"

    unset pass1 pass2
    yes_no "The system should be ready to reboot, Continue (Y/N): " || exit 0
    reboot
}

### Handling arguments ###

if [[ $# -lt 1 ]]; then
    print_help
    exit 1
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        "help") help=true; shift;;

        "arch-install")
            [ -z "$2" ] && eprint "\`arch-install\` -> you should provide a 'parition_mode' (vm, main, X220, mounted)."
            args_arch_install=true
            # shellcheck disable=2015
            re_match "$2" "^(vm|main|x220|mounted)$" && partition_mode="$2" || eprint "'$2' is not a valid partitioning mode."
            shift 2
            ;;

        "install-dotfiles")
            args_install_dotfiles=true 
            # shellcheck disable=2034
            [ -n "$2" ] && dotfiles_url="$2" && shift 2 && continue
            ;;

        "install-aurhelper")
            [ -z "$2" ] && eprint "\`install-aurhelper\` -> you should provide a 'aurhelper' (yay, paru)."
            args_install_aurhelper=true 
            # shellcheck disable=2015,2034
            re_match "$2" "^(yay|paru)$" && aurhelper="$2" || eprint "'$2' is not a valid aurhelper."
            shift 2
            ;;

        "install-programs")
            args_install_programs=true
            [ -z "$2" ] && programs="ALL" && shift && continue
            # shellcheck disable=2015,2034
            re_match "$2" "^(X11|DWM|WAYLAND|HYPRLAND|DEV|PYTHON|CLANG|LUA|BASH|JS|EXTRA|VIRT|ALL)$" && programs="$2" || eprint "'$2' is not a valid tag."
            shift 2
            ;;

        "configure") args_configure=true; shift;;

        "experimental-clean-home") args_clean_home=true; shift;;

        "backup")
            args_backup=true
            [ -z "$2" ] && backup_name="backup_$(date "+%Y-%m-%d_%H:%M")" && shift && continue
            # shellcheck disable=2015,2034
            re_match "$2" "$regex_valid_directory" && backup_name="$2" || eprint ""
            shift 2
            ;;

        "update-mirrors") args_update_mirrors=true; shift;;

        "install") args_install=true; shift;;

        "-v"|"--verbose") verbose=true; cmd_suffix=""; shift;;

        "-q"|"--quiet") quiet=true; shift;;

        "-u"|"--username")
            if [ -z "$2" ]; then
                eprint "'-u' -> You should provide a username."
            fi
            username="$2"
            if ! re_match "$username" "$regex_valid_username"; then
                eprint "Username '$username' is not valid.\nGive a username beginning with a letter, with only lowercase letters, - or _."
            fi
            shift 2
            ;;

        "-h"|"--hostname")
            if [ -z "$2" ]; then
                eprint "'-h' -> You should provide a hostname."
            fi
            hostname="$2"
            if ! re_match "$hostname" "$regex_valid_hostname"; then
                eprint "Hostname '$hostname' is not valid.\nGive a hostname beginning with a letter, with only lowercase letters, - or _."
            fi
            shift 2
            ;;

        "-t"|"--timezone")
            if [ -z "$2" ]; then
                eprint "'-t' -> You should provide a timezone."
            fi
            timezone="$2"
            if ! [ -f "/usr/share/zoneinfo/$timezone" ]; then
                eprint "Timezone '$timezone' is not valid.\nView valid timezones: \`timezonectl list-timezones\`"
            fi
            shift 2
            ;;

        *) invalid_option "$1";;
    esac
done

$verbose && $quiet && eprint "Can't use '-v' with '-q'."

# Set username to current user, unless running by root or explicitly specifying the username through arguments.
! isRoot && [ -z "$username" ] && username="$(id -un)"

# If running as root through `sudo`; set username to $SUDO_USER 
isRoot && [ -n "$SUDO_USER" ] && username="$SUDO_USER"

# Set hostname to current hostname if not already provided.
[ -z "$hostname" ] && hostname="$(hostnamectl hostname 2>/dev/null || cat /etc/hostname)"

[ -n "$help" ] && print_help && exit 0

[ -n "$args_arch_install" ] && {
    is_archlinux || eprint "Can only install an ArchLinux system."
    isRoot || eprint "Only root can install the system."
    ensure_mount_point && yes_no "Continuing will result in your data being lost. Continue? (Y/N): " && eval "partition_$partition_mode"
    arch_install
    exit
}

[[ -n "$args_install_dotfiles" ]] && command_install_dotfiles

[[ -n "$args_install_aurhelper" ]] && command_install_aurhelper

[[ -n "$args_install_programs" ]] && command_install_programs

[[ -n "$args_configure" ]] && command_configure

[[ -n "$args_clean_home" ]] && command_experimental_clean_home

[[ -n "$args_backup" ]] && command_backup

[[ -n "$args_update_mirrors" ]] && command_update_mirrors

[ -n "$args_install" ] && {
    is_archlinux || eprint "Not running ArchLinux."
    isRoot || eprint "Only root can install $program_name."
    check_internet_connection || eprint "Can't reach the web."
    
    mkdir -p "$install_path"
    curl "https://raw.githubusercontent.com/themamiza/mais/refs/heads/main/mais" > "$install_path/$program_name"
    chmod 755 "$install_path/$program_name"
}
